spring.application.name=Batch_Viejito
# 1. CONEXIÓN A ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=M@t@d0r5412
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. RUTA DE SALIDA (Para el archivo TXT)
# Usamos doble diagonal inversa para Windows
ruta.archivo.salida=C:\\DEVOPS\\candidatos_platino.txt

# 3. CONFIGURACIÓN DE LOGS
logging.level.org.springframework.jdbc=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n